### ISSUE TITLE
unable to run on ubuntu 18.04

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [Co-Epi/mobile-app#14]
i am getting this error while running it on ubuntu 18.04

**java.lang.Throwable: No bluetooth adapter. Can't continue.**

i followed the instructions as mention in READ.ME

**Comment by HamzaBinSarfraz** [comment]
this repo is under development nevermind

**Comment by i-schuetz** [comment]
The emulator doesn't support bluetooth.
