### ISSUE TITLE
Why did you choose to go native?

### ISSUE THREAD

**Issue by Nautman** [Co-Epi/mobile-app#17]
Hi!

I have been following the developments of Co-Epi, Covid Watch and Private Kit for the past week. I am wondering why you decided to go native and abandon React Native?

I think your project is really interesting!

Thanks.

**Comment by ivnsch** [comment]
Sorry for the late reply. For the most part it was the setup of the team at different points of time. The initial members, that created the RN project, left and new members were more experienced with native. In the meantime we've been exploring more meaningful ways to do cross-platform, with a shared Rust library, that provides better performance, safety and inter-op with the TCN reference implementation, which is also written in Rust.
