### ISSUE TITLE
In android not getting the CEN key from IOS devices.

### ISSUE THREAD

**Issue by Zuhadather** [Co-Epi/mobile-app#18]
Hi Team , 

I took the source code and I am trying to the scan from the iOS device.
I am not getting any key generated. More over in scanResults. 
In BLEScanner class --> 
var contactEventIdentifier is coming us null if interacting with IOS device( when the app in foreground state itself ).
 but the iOS device can get the key from android at the same time.

Any fix for this ?  Please let me know.

**Comment by ivnsch** [comment]
As stated in the Readme, this repo / the React Native app isn't maintained anymore. This is a very early stage prototype btw, barely functional.

**Comment by Zuhadather** [comment]
> As stated in the Readme, this repo / the React Native app isn't maintained anymore. This is a very early stage prototype btw, barely functional.

Yes wrongly raised issue here. Sorry about that.
will close it now.
